---
title: "Sedap-INEP - Projeto tales.6387"
format: html
---

Este script tem como objetivo acompanhar, testar e documentar, do lado de fora da sala segura do INEP, o desenvolvimento do código que está sendo elaborado internamente.

A intenção é que, caso tudo transcorra como previsto, possamos extrair o script final — atualmente sendo desenvolvido em um documento Quarto dentro da sala — para uso e replicação externa.

Além disso, este documento funciona como um caderno de campo: serve tanto para preparar materiais a serem utilizados dentro da sala quanto para registrar os avanços realizados no ambiente restrito, facilitando o acompanhamento e a reconstrução do trabalho fora dele.

# Início do Script

O Script se inicia na sala do Sedap com: 1. Definição do Diretório de Trabalho (especialmente importante pois lá não é possível usar Rproject e temos que salvar os arquivos em pastas específicas ou ele pode ser deletado). Os dados ficam disponíveis via acesso na rede em disco de nome "T:/"

Depis demos que verificar se os pacotes necessário s do tidyverse foram instalados, se não é imporssível ler os bancos de dados CSV

```{R}

getwd()
setwd("T:/")
installed.packages()

```

Os pacotes na sala do INEP não podem ser baixados via CRAN, ao invés disso eles são disponibilziados em arquivos diretamente no computador, que, no entanto, ainda não tive acesso.

```{R}

#Código de instalação dos pacotes no R do Sedap

```

Depois de instalar os pacotes podemos finalmente ler as bases de dados usando a função readr

```{R}

readr::read_delim("1. Bases Enem\ENEM_2010.csv", delim=";")
#Essa forma de leitura se repete para todas as outras bases

```



